### ISSUE TITLE
Configure Git Actions for project

### ISSUE THREAD

**Issue by Kacperfis** [coders-school/password-manager#1]
configure actions for build + ut

@kawapa
@emttiew

**Comment by emttiew** [comment]
- [x] Trigger build and UT on push
- [x] Trigger build and UT on PR
- [x] Manually trigger build and UT
- [ ] Save artifacts (binary, logs?)
- [ ] Add a badge to display workflow status? [link](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge)
